plps_pull () {
    PSPL_PROJECT_NAME=$1
    TARBALL_PATH=/$PSPL_REMOTE_PATH/$PSPL_PROJECT_NAME.tar.gz

    mv $PSPL_LOCAL_PATH/$PSPL_PROJECT_NAME/venv $PSPL_LOCAL_PATH
    mv $PSPL_LOCAL_PATH/$PSPL_PROJECT_NAME/.idea $PSPL_LOCAL_PATH
    rm -rf $PSPL_LOCAL_PATH/$PSPL_PROJECT_NAME

    scp $PSPL_REMOTE_USER@$PSPL_REMOTE_SERVER:$PSPL_REMOTE_PATH/TARBALL_PATH $PSPL_LOCAL_PATH

    rm -rf $PSPL_LOCAL_PATH/$PSPL_PROJECT_NAME/venv
    rm -rf $PSPL_LOCAL_PATH/$PSPL_PROJECT_NAME/.idea
    mv $PSPL_LOCAL_PATH/venv $PSPL_LOCAL_PATH/$PSPL_PROJECT_NAME
    mv $PSPL_LOCAL_PATH/.idea $PSPL_LOCAL_PATH/$PSPL_PROJECT_NAME
}

plps_push () {
    PSPL_PROJECT_NAME=$1
    TARBALL_PATH=/tmp/$PSPL_PROJECT_NAME.tar.gz

    rm $TARBALL_PATH
    cd ~/dev/$PSPL_PROJECT_NAME
    tar czf $TARBALL_PATH .

    scp $TARBALL_PATH $PSPL_REMOTE_USER@$PSPL_REMOTE_SERVER:$PSPL_REMOTE_PATH
}

alias push="plps_push $1"
alias pull="plps_pull $1"